kind: pipeline
type: docker
name: latest 

steps:
- name: publish
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    dockerfile: latest/Dockerfile
    context: latest/
    build-args:
      - HASTEBIN_VERSION=master
    purge: true
    repo: modem7/hastebin
    tags: latest

trigger:
  event:
  - cron
  cron:
  - hastebin_latest

---

kind: pipeline
type: docker
name: stable

steps:
- name: publish
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    dockerfile: stable/Dockerfile
    context: stable/
    build-args:
      - HASTEBIN_VERSION=master
    purge: true
    repo: modem7/hastebin
    tags: stable

trigger:
  event:
  - cron
  cron:
  - hastebin_stable
