kind: pipeline
type: docker
name: latest 

platform:
  os: linux
  arch: amd64

steps:
- name: publish
  image: plugins/docker
  privileged: true
  settings:
    repo: modem7/hastebin
    tags: latest
    platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8
    purge: true
    # cache_from: "modem7/hastebin:latest"
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    dockerfile: latest/Dockerfile
    context: latest/
    build-args:
      - HASTEBIN_VERSION=master

# trigger:
  # event:
  # - cron
  # cron:
  # - hastebin_latest

---

kind: pipeline
type: docker
name: stable 

platform:
  os: linux
  arch: amd64

steps:
- name: publish
  image: plugins/docker
  privileged: true
  settings:
    repo: modem7/hastebin
    tags: stable
    platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8
    purge: true
    # cache_from: "modem7/hastebin:stable"
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    dockerfile: stable/Dockerfile
    context: stable/
    build-args:
      - HASTEBIN_VERSION=master

# trigger:
  # event:
  # - cron
  # cron:
  # - hastebin_stable
